version: '3.9'

services:
 nodejs:
    image: nodejs
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 5000:5000
    networks:
      - backend   
    restart: unless-stopped
    env_file:
      - .env
networks:
  backend: